name: WorldTimeBlocker
main: SmallkingDev\WorldTimeBlocker\Main
src-namespace-prefix: SmallkingDev\WorldTimeBlocker
version: 1.2.0
api: [4.0.0, 5.0.0]
author: SmallkingDev
description: Block world time
website: https://github.com/smallkingdev-pm-pl/WorldTimeBlocker
